### ISSUE TITLE
Error in README

### ISSUE THREAD

**Issue by adampasz** [Snapkite/snapkite-engine#10]
```
git clone https://github.com/snapkite/snapkite.git
```
should be 
```
git clone https://github.com/snapkite/snapkite.git
```

**Comment by fedosejev** [comment]
@adampasz they're the same?

**Comment by adampasz** [comment]
Oops.

git clone https://github.com/snapkite/snapkite-engine.git

Sorry, didn't have coffee yet.

FYI, snapkite is used in React.js Essentials from O'Reilly.

**Comment by fedosejev** [comment]
@adampasz thanks, fixed.

Yeah, I am the author of [React.js Essentials](https://www.packtpub.com/web-development/reactjs-essentials) (published by Packt Publishing).

**Comment by adampasz** [comment]
Oh. Duh. :)
